### ISSUE TITLE
No son problemas, son mejoras de performance. 

### ISSUE THREAD

**Issue by Seba-san** [PabloF7/noter#1]
Cuando esta mal configurada la velocidad, la terminal no muestra nada. En general cuando hay un problema con la configuración de la velocidad, la terminal te muestra caracteres raros, inesperados. Es una especie de feedback para saber porque no funciona.  

Otra mejora es la posibilidad de activar o desactivar el puerto con una tecla de acceso rápido o mediante el panel principal (no desde la configuración). 

Es bastante incomodo que en el panel principal no te muestre la configuración actual.

**Comment by doquen** [comment]
> Cuando esta mal configurada la velocidad, la terminal no muestra nada. En general cuando hay un problema con la configuración de la velocidad, la terminal te muestra caracteres raros, inesperados. Es una especie de feedback para saber porque no funciona.

En el programa no se hizo nada para quitar caracteres en caso de problemas de velocidad. Quizás sea tema de la biblioteca QSerialPort que no muestra nada si no están bien las velocidades. Voy a ver si se puede hacer algo.

> Otra mejora es la posibilidad de activar o desactivar el puerto con una tecla de acceso rápido o mediante el panel principal (no desde la configuración).

Te referís a un shortcut para conectar con una configuración por defecto? La idea de tener la pantalla de configuración separada es para poder usarlo en modo consola. Se podría hacer un atajo de teclado que te lleve a la configuración, o un atajo que te deje conectarte a una configuración pre-guardada.. algo así?

> Es bastante incomodo que en el panel principal no te muestre la configuración actual.

Agregar la configuración actual en la barra de títulos serviría?

**Comment by Seba-san** [comment]
> > Cuando esta mal configurada la velocidad, la terminal no muestra nada. En general cuando hay un problema con la configuración de la velocidad, la terminal te muestra caracteres raros, inesperados. Es una especie de feedback para saber porque no funciona.
> 
> En el programa no se hizo nada para quitar caracteres en caso de problemas de velocidad. Quizás sea tema de la biblioteca QSerialPort que no muestra nada si no están bien las velocidades. Voy a ver si se puede hacer algo.
> 
Joya.
> > Otra mejora es la posibilidad de activar o desactivar el puerto con una tecla de acceso rápido o mediante el panel principal (no desde la configuración).
> 
> Te referís a un shortcut para conectar con una configuración por defecto? La idea de tener la pantalla de configuración separada es para poder usarlo en modo consola. Se podría hacer un atajo de teclado que te lleve a la configuración, o un atajo que te deje conectarte a una configuración pre-guardada.. algo así?
>
Me refiero a que si usas Arduino y estas programando y testeando, necesitas desconectar el puerto para poder programarlo; luego volver a conectarlo para probarlo. Hace la prueba de programar un arduino para que te envie algo por serial. Vas a entender a lo que me refiero.
> > Es bastante incomodo que en el panel principal no te muestre la configuración actual.
> 
> Agregar la configuración actual en la barra de títulos serviría?

Si. Con poner el nombre del puerto, la velocidad, si esta conectado o no y alguna que otra posibilidad. Mientras mas simple quede mejor. No probé el modo consola.

**Comment by doquen** [comment]
>Cuando esta mal configurada la velocidad, la terminal no muestra nada. En general cuando hay un problema con la configuración de la velocidad, la terminal te muestra caracteres raros, inesperados. Es una especie de feedback para saber porque no funciona.
>>En el programa no se hizo nada para quitar caracteres en caso de problemas de velocidad. Quizás sea tema de la biblioteca QSerialPort que no muestra nada si no están bien las velocidades. Voy a ver si se puede hacer algo.
>>>Joya.

Sabes que a mi se me muestra caracteres? Según lo que busque, los caracteres raros te aparecen solo si la diferencia de velocidades no es tanta (de 9600 a 19200 por ej). Adjunto imagen:
![imagen](https://user-images.githubusercontent.com/20048049/45621152-bf57f800-ba55-11e8-91d4-58e30187519d.png)

>Otra mejora es la posibilidad de activar o desactivar el puerto con una tecla de acceso rápido o mediante el panel principal (no desde la configuración).
>>Te referís a un shortcut para conectar con una configuración por defecto? La idea de tener la pantalla de configuración separada es para poder usarlo en modo consola. Se podría hacer un atajo de teclado que te lleve a la configuración, o un atajo que te deje conectarte a una configuración pre-guardada.. algo así?
>>>Me refiero a que si usas Arduino y estas programando y testeando, necesitas desconectar el puerto para poder programarlo; luego volver a conectarlo para probarlo. Hace la prueba de programar un arduino para que te envie algo por serial. Vas a entender a lo que me refiero.

Agregué un botón para conectar y desconectar, con shortcut Alt+C

>Es bastante incomodo que en el panel principal no te muestre la configuración actual.
>>Agregar la configuración actual en la barra de títulos serviría?
>>>Si. Con poner el nombre del puerto, la velocidad, si esta conectado o no y alguna que otra posibilidad. Mientras mas simple quede mejor. No probé el modo consola.

Agregué puerto, baudios y estado en el título de la consola
