### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by Seba-san** [PabloF7/noter#2]
No se si corresponde pedirlo por aca o no. 
De 19 notebook de un curso de estudiantes de secundaria, 2 pc son MAC con sistema IOS. En la sección de downloads, sólo están compilados para linux y para windows. Desconozco la dificultad de crear uno para IOS. Me sería útil poder incorporarlo en esos sistemas también.  
gracias!

**Comment by azagaya** [comment]
Hola,
Yo no tengo MAC asi que no puedo hacerlo ni se la dificultad que tendría. Dame unos días que me fijo si puedo hacerlo en una maquina virtual y te aviso. O por ahi hay alguna forma de compilarlo de dorma cruzada desde linux. Si tenes una MAC a disposicion podes intentar instalar qt creator y compilarlo sino.

**Comment by Seba-san** [comment]
no tengo una MAC, un estudiante la tiene... me parece muy invasivo pedirle que lo compile. Es más fácil usar otro programa (si resulta muy difícil hacer la compilación cruzada).

**Comment by doquen** [comment]
Hola,
Por lo que estuve viendo, la compilación cruzada no sería posible (o demasiado complicada para mí). Utilizar una máquina virtual con Mac en una notebook que no sea de apple es ilegal, así que esa opción tampoco es válida. Un conocido con mac pudo compilar correctamente la aplicación, pero no tiene nada con que probar si funciona la comunicación serie. Lo que puedo hacer es pedirle que intente generar un binario y subirlo a release, pero no sabemos si va a andar en una Mac que no tenga todas las bibliotecas instaladas hasta probarlo. Por lo que probablemente tengas que probarlo en la notebook de tu alumno varias veces y mandarme los mensajes de error que salgan en caso de que falle, y así ir solucionando los problemas de a uno.

Por otro lado, si tu alumno instala Qt Creator (versión open source) y luego abre este proyecto (tmb open source) debería poder correrlo desde el IDE sin problema.

Si alguna de estas soluciones te sirve, comentalo acá y vemos como seguimos.

**Comment by doquen** [comment]
pueden intentar si esta anda
 https://mega.nz/#!uuBh3YZJ!2Nh-YdNgZorE19LQ1tr4D0Mpe1kkLpjminQ2RbetScw

compilado para Mac OS high Sierra

**Comment by doquen** [comment]
Avisame si te funcionó la aplicación en MAC. Por otra parte, actualicé en releases los binarios para linux y windows, porque tenian un bug

**Comment by Seba-san** [comment]
Hoy los probé en clase, en ninguna pc funcionó. En ambas carga el programa, en una se cuelga cuando le das a conectar y en la otra  les aparece "conexión exitosa" pero no aparecen los datos. Los chicos dicen que buscaron Terminales seriales para MAC y dicen que son todas pagas, por lo que estan medios atados de manos. Sin embargo usamos la terminal de eclipse y salio andando. (el terminal de eclipse tiene bugs de mucha antiguedad, por eso preferentemente no lo considero como primer opción).

**Comment by doquen** [comment]
Hola,
Y la versión nueva de Windows y Linux si andan? capaz que metí un bug con la última actualización.
Otro tema, es posible que los usuarios de Mac (así como los de linux) necesiten darle permisos a los puerto serie.

**Comment by Seba-san** [comment]
Las versiones de septiembre de  linux y windows  funcionaban bien (no detecte ningún problema aún). 
No probé con las nuevas versiones.

**Comment by azagaya** [comment]
La versión de MAC esta compilada con el ultimo commit, que es el mismo que las versiones nuevas de windows y linux. Por eso decia que es posible que haya metido un error en la ultima versión y por eso no ande la de MAC.

**Comment by doquen** [comment]
La versión de MAC es la misma versión que las últimas de windows y linux.
Por eso decía que es posible que sea una falla de la ultima versión,  y no de la plataforma para la que fue compilado.. 
Por otra parte, si pueden en mac ejecutar desde la consola la aplicación y mandarme los mensajes que aparecen sería muy util

**Comment by Seba-san** [comment]
Hoy revise bien como lo estaban ejecutando, al parecer era un problema de la pc. Hoy quedo andando en las 2 MAC (y), ademas probé la última versión en linux  y anda joya.

**Comment by doquen** [comment]
Perfecto, agrego la version de Mac a las releases entonces
